// MapMenu: overlay control that shows a hamburger menu with checkboxes per track
export default class MapMenu {
        // Static array of 64 saturated, easily distinguishable RGB colours. Generated by tools/show_colours.py
        static trackColours = [
            "#ff9000", "#3c28f6", "#28f628", "#28cdf6", "#f628aa", "#f9ec76", "#08ba79", "#b376f9", "#ba0843",
            "#79ba08", "#ba7f08", "#ef28f6", "#f99976", "#28f6e8", "#f976a6", "#76f97f", "#e1f628", "#7f08ba",
            "#f6bf28", "#f976e8", "#f62843", "#c5f976", "#9df628", "#ba08ae", "#08ba2b", "#baba08", "#f9c076",
            "#ba086d", "#76f9bc", "#08baba", "#0890ba", "#ba0e08", "#f9767a", "#f68828", "#f6287a", "#ba5508",
            "#aa28f6", "#2b08ba", "#f6e128", "#28f69d", "#76ecf9", "#28f65f", "#f628d4", "#ba9c08", "#08ba55",
            "#08ba9c", "#ba088b", "#f976c5", "#f6a328", "#f63528", "#f6285f", "#ba082b", "#df76f9", "#8376f9",
            "#f9d676", "#08a2ba", "#28f6cd", "#e8f976", "#9cba08", "#73f628", "#4fba08", "#28f681", "#bff628",
            "#a2f976"
        ];

    /**
     * @param {google.maps.Map} map
     * @param {Array} tracks - Array of track metadata objects {id, pointCount}
     * @param {Function} onChange - Callback (trackId, checked) when checkbox toggled
     */
    constructor(map, tracks = [], onChange = () => {}) {
        this.map = map;
        this.onChange = onChange;
        this.container = document.createElement('div');
        this.container.className = 'map-menu-container';

        // Header / hamburger button
        this.header = document.createElement('div');
        this.header.className = 'map-menu-header';
        this.hamburger = document.createElement('div');
        this.hamburger.className = 'map-menu-hamburger';
        this.hamburger.innerHTML = '&#9776;'; // simple hamburger
        this.title = document.createElement('div');
        this.title.className = 'map-menu-title';
        this.title.textContent = 'Tracks';
        this.header.appendChild(this.hamburger);
        this.header.appendChild(this.title);
        this.container.appendChild(this.header);

        // Body (checkbox list)
        this.body = document.createElement('div');
        this.body.className = 'map-menu-body';
        this.container.appendChild(this.body);

        // Toggle body visibility when header clicked
        this.header.addEventListener('click', () => {
            this.container.classList.toggle('open');
        });

        // Insert into map controls
        this.map.controls[google.maps.ControlPosition.TOP_LEFT].push(this.container);

        this.checkboxes = new Map();
        this.setTracks(tracks);
    }

    /**
     * Replace the track list in the menu
     * @param {Array} tracks
     */
    setTracks(tracks = []) {
        // Clear existing
        this.body.innerHTML = '';
        this.checkboxes.clear();

        // create the show/hide all control (inserted after rows are created)
        let allControlBtn = null;

        // Create a list item for each track
        tracks.forEach(track => {
            const row = document.createElement('div');
            row.className = 'map-menu-row';

            const input = document.createElement('input');
            input.type = 'checkbox';
            input.dataset.trackId = track.id;
            input.className = 'map-menu-checkbox';

            const label = document.createElement('label');
            label.textContent = `${track.id} (${track.pointCount || 0})`;
            label.className = 'map-menu-label';

            input.addEventListener('change', (ev) => {
                const checked = ev.target.checked;
                const trackId = ev.target.dataset.trackId;
                try {
                    this.onChange(trackId, checked);
                } catch (err) {
                    console.error('Error in MapMenu onChange handler:', err);
                }
            });

            // clicking label toggles checkbox via label click handler below
            // keep rows non-focusable by default

            // clicking label toggles checkbox
            label.addEventListener('click', () => input.click());

            row.appendChild(input);
            row.appendChild(label);
            this.body.appendChild(row);

            this.checkboxes.set(track.id, input);
        });

        // Now create the show/hide-all control and insert it at the top
        const controlRow = document.createElement('div');
        controlRow.className = 'map-menu-all-row';
        allControlBtn = document.createElement('button');
        allControlBtn.type = 'button';
        allControlBtn.className = 'map-menu-all-button';
        // Determine initial label
        const anyUnchecked = Array.from(this.checkboxes.values()).some(i => !i.checked);
        allControlBtn.textContent = anyUnchecked ? 'Show all' : 'Hide all';
        allControlBtn.addEventListener('click', () => {
            const inputs = Array.from(this.checkboxes.entries());
            const shouldCheck = inputs.some(([id, input]) => !input.checked); // if any unchecked, we should check all
            inputs.forEach(([id, input]) => {
                if (input.checked !== shouldCheck) {
                    input.checked = shouldCheck;
                    try { this.onChange(id, shouldCheck); } catch (e) { console.error('MapMenu all toggle onChange error', e); }
                }
            });
            allControlBtn.textContent = shouldCheck ? 'Hide all' : 'Show all';
        });
        controlRow.appendChild(allControlBtn);
        // insert at top
        if (this.body.firstChild) {
            this.body.insertBefore(controlRow, this.body.firstChild);
        } else {
            this.body.appendChild(controlRow);
        }
    }

    /**
     * Programmatically set checkbox state for a track
     * @param {string} trackId
     * @param {boolean} checked
     */
    setChecked(trackId, checked) {
        const input = this.checkboxes.get(trackId);
        if (input) input.checked = !!checked;
    }

    // no toggle/keyboard helper methods

    destroy() {
        try {
            // Remove from map controls
            const controls = this.map.controls[google.maps.ControlPosition.TOP_LEFT];
            for (let i = 0; i < controls.getLength(); i++) {
                if (controls.getAt(i) === this.container) {
                    controls.removeAt(i);
                    break;
                }
            }
            // no global handlers to remove
        } catch (err) {
            // ignore
        }
    }
}
